stages:
  - build_test
  - test
  - deploy

include:
  - template: SAST.gitlab-ci.yml

build:
  stage: build_test
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-} || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-} --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-} .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-}

test:
  stage: build_test
  image: python:3.10
  variables:
    DJANGO_SECRET_KEY: abcdef
    TEST_DATABASE_URL: postgis://kobo:kobo@postgres:5432/kobocat_test
    REDIS_SESSION_URL: redis://redis_cache:6379/2
    CACHE_URL: redis://redis_cache:6379/3
    USE_POSTGRESQL: "True"
    POSTGRES_USER: kobo
    POSTGRES_PASSWORD: kobo
    POSTGRES_DB: kobocat_test
    SERVICE_ACCOUNT_BACKEND_URL: redis://redis_cache:6379/4
  services:
    - name: postgis/postgis:14-3.2
      alias: postgres
    - name: redis:6.2
      alias: redis_cache
  script:
    - apt-get update && apt-get install -y ghostscript gdal-bin libproj-dev gettext openjdk-17-jre
    - pip install -r dependencies/pip/dev_requirements.txt
    - pytest -vv -rf

deploy-beta:
  stage: deploy
  image:
    name: alpine/helm:3.12.0
    entrypoint: [""]
  script:
    - helm repo add kobo https://gitlab.com/api/v4/projects/32216873/packages/helm/stable
    - helm -n kobo-dev upgrade beta kobo/kobo --atomic --set-string kobocat.image.tag=${CI_COMMIT_SHORT_SHA} --reuse-values
  environment:
    name: beta
    url: https://kc.beta.kobotoolbox.org
  only:
    refs:
      - public-beta
      - gitlab-ci-build
    variables:
      - $CI_COMMIT_REF_PROTECTED
