sudo: false
language: python
python:
- '2.7'
script:
- 
after_success:
- test "$TRAVIS_PULL_REQUEST" == 'false' || exit 0
- test "$TRAVIS_BRANCH" == 'master' || exit 0
- echo '*** Deploying to staging server'
- openssl aes-256-cbc -K $encrypted_cddd71e0ad67_key -iv $encrypted_cddd71e0ad67_iv
  -in .travis/staging_deploy_key.pem.enc -out .travis/staging_deploy_key.pem -d
- chmod 600 .travis/staging_deploy_key.pem
- eval "$(ssh-agent)"
- ssh-add .travis/staging_deploy_key.pem
- ssh -o UserKnownHostsFile=.travis/staging_known_host ubuntu@kc.kbtdev.org /home/ubuntu/scripts/deploy.sh kobocat "$TRAVIS_COMMIT"
notifications:
  irc: irc.freenode.org#kobotest
  flowdock: ad631fc562736cf87e0c4439f9518f9d
